/**
 * Spendly Constants — Currencies
 *
 * All 180 official world currencies with symbols, locales, and flags.
 */

import type { CurrencyInfo } from '../types/settings';

export const currencies: CurrencyInfo[] = [
  { code: 'USD', name: 'US Dollar', symbol: '$', locale: 'en-US', flag: '🇺🇸' },
  { code: 'EUR', name: 'Euro', symbol: '€', locale: 'de-DE', flag: '🇪🇺' },
  { code: 'GBP', name: 'British Pound', symbol: '£', locale: 'en-GB', flag: '🇬🇧' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', locale: 'ja-JP', flag: '🇯🇵' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', locale: 'zh-CN', flag: '🇨🇳' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', locale: 'en-IN', flag: '🇮🇳' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', locale: 'en-CA', flag: '🇨🇦' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', locale: 'en-AU', flag: '🇦🇺' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', locale: 'de-CH', flag: '🇨🇭' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', locale: 'ko-KR', flag: '🇰🇷' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', locale: 'en-SG', flag: '🇸🇬' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', locale: 'en-HK', flag: '🇭🇰' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', locale: 'sv-SE', flag: '🇸🇪' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', locale: 'nb-NO', flag: '🇳🇴' },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', locale: 'da-DK', flag: '🇩🇰' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', locale: 'en-NZ', flag: '🇳🇿' },
  { code: 'MXN', name: 'Mexican Peso', symbol: 'MX$', locale: 'es-MX', flag: '🇲🇽' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', locale: 'pt-BR', flag: '🇧🇷' },
  { code: 'ARS', name: 'Argentine Peso', symbol: 'AR$', locale: 'es-AR', flag: '🇦🇷' },
  { code: 'CLP', name: 'Chilean Peso', symbol: 'CL$', locale: 'es-CL', flag: '🇨🇱' },
  { code: 'COP', name: 'Colombian Peso', symbol: 'CO$', locale: 'es-CO', flag: '🇨🇴' },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', locale: 'es-PE', flag: '🇵🇪' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', locale: 'en-ZA', flag: '🇿🇦' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', locale: 'en-NG', flag: '🇳🇬' },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', locale: 'en-GH', flag: '🇬🇭' },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', locale: 'en-KE', flag: '🇰🇪' },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', locale: 'en-UG', flag: '🇺🇬' },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', locale: 'sw-TZ', flag: '🇹🇿' },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', locale: 'am-ET', flag: '🇪🇹' },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', locale: 'ar-EG', flag: '🇪🇬' },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD', locale: 'ar-MA', flag: '🇲🇦' },
  { code: 'XOF', name: 'West African CFA', symbol: 'CFA', locale: 'fr-SN', flag: '🇸🇳' },
  { code: 'XAF', name: 'Central African CFA', symbol: 'FCFA', locale: 'fr-CM', flag: '🇨🇲' },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', locale: 'rw-RW', flag: '🇷🇼' },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', locale: 'en-ZM', flag: '🇿🇲' },
  { code: 'BWP', name: 'Botswana Pula', symbol: 'P', locale: 'en-BW', flag: '🇧🇼' },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', locale: 'pt-MZ', flag: '🇲🇿' },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', locale: 'pt-AO', flag: '🇦🇴' },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', locale: 'tr-TR', flag: '🇹🇷' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', locale: 'ru-RU', flag: '🇷🇺' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', locale: 'uk-UA', flag: '🇺🇦' },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', locale: 'pl-PL', flag: '🇵🇱' },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', locale: 'cs-CZ', flag: '🇨🇿' },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', locale: 'hu-HU', flag: '🇭🇺' },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', locale: 'ro-RO', flag: '🇷🇴' },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', locale: 'bg-BG', flag: '🇧🇬' },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', locale: 'hr-HR', flag: '🇭🇷' },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'din', locale: 'sr-RS', flag: '🇷🇸' },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', locale: 'is-IS', flag: '🇮🇸' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', locale: 'ar-AE', flag: '🇦🇪' },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', locale: 'ar-SA', flag: '🇸🇦' },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'QR', locale: 'ar-QA', flag: '🇶🇦' },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD', locale: 'ar-KW', flag: '🇰🇼' },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BD', locale: 'ar-BH', flag: '🇧🇭' },
  { code: 'OMR', name: 'Omani Rial', symbol: 'OMR', locale: 'ar-OM', flag: '🇴🇲' },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', locale: 'ar-JO', flag: '🇯🇴' },
  { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', locale: 'he-IL', flag: '🇮🇱' },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'L£', locale: 'ar-LB', flag: '🇱🇧' },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', locale: 'en-PK', flag: '🇵🇰' },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', locale: 'bn-BD', flag: '🇧🇩' },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', locale: 'si-LK', flag: '🇱🇰' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs', locale: 'ne-NP', flag: '🇳🇵' },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', locale: 'th-TH', flag: '🇹🇭' },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', locale: 'vi-VN', flag: '🇻🇳' },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', locale: 'ms-MY', flag: '🇲🇾' },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', locale: 'id-ID', flag: '🇮🇩' },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', locale: 'en-PH', flag: '🇵🇭' },
  { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$', locale: 'zh-TW', flag: '🇹🇼' },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', locale: 'my-MM', flag: '🇲🇲' },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', locale: 'km-KH', flag: '🇰🇭' },
  { code: 'LAK', name: 'Lao Kip', symbol: '₭', locale: 'lo-LA', flag: '🇱🇦' },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', locale: 'mn-MN', flag: '🇲🇳' },
  { code: 'KZT', name: 'Kazakh Tenge', symbol: '₸', locale: 'kk-KZ', flag: '🇰🇿' },
  { code: 'UZS', name: 'Uzbek Som', symbol: 'сўм', locale: 'uz-UZ', flag: '🇺🇿' },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', locale: 'ka-GE', flag: '🇬🇪' },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', locale: 'hy-AM', flag: '🇦🇲' },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', locale: 'az-AZ', flag: '🇦🇿' },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', locale: 'ar-IQ', flag: '🇮🇶' },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', locale: 'fa-IR', flag: '🇮🇷' },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', locale: 'ps-AF', flag: '🇦🇫' },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', locale: 'es-DO', flag: '🇩🇴' },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', locale: 'es-CR', flag: '🇨🇷' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', locale: 'es-GT', flag: '🇬🇹' },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', locale: 'es-HN', flag: '🇭🇳' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', locale: 'es-NI', flag: '🇳🇮' },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', locale: 'es-PA', flag: '🇵🇦' },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', locale: 'es-UY', flag: '🇺🇾' },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', locale: 'es-PY', flag: '🇵🇾' },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', locale: 'es-BO', flag: '🇧🇴' },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.S', locale: 'es-VE', flag: '🇻🇪' },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', locale: 'en-JM', flag: '🇯🇲' },
  { code: 'TTD', name: 'Trinidad Dollar', symbol: 'TT$', locale: 'en-TT', flag: '🇹🇹' },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: 'Bds$', locale: 'en-BB', flag: '🇧🇧' },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: 'B$', locale: 'en-BS', flag: '🇧🇸' },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', locale: 'fr-HT', flag: '🇭🇹' },
  { code: 'CUP', name: 'Cuban Peso', symbol: '$MN', locale: 'es-CU', flag: '🇨🇺' },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', locale: 'en-BZ', flag: '🇧🇿' },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: 'SRD', locale: 'nl-SR', flag: '🇸🇷' },
  { code: 'GYD', name: 'Guyanese Dollar', symbol: 'G$', locale: 'en-GY', flag: '🇬🇾' },
  { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', locale: 'en-FJ', flag: '🇫🇯' },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', locale: 'en-PG', flag: '🇵🇬' },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', locale: 'sm-WS', flag: '🇼🇸' },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', locale: 'to-TO', flag: '🇹🇴' },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', locale: 'en-VU', flag: '🇻🇺' },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', locale: 'en-SB', flag: '🇸🇧' },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', locale: 'en-SC', flag: '🇸🇨' },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', locale: 'en-MU', flag: '🇲🇺' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', locale: 'dv-MV', flag: '🇲🇻' },
  { code: 'BND', name: 'Brunei Dollar', symbol: 'B$', locale: 'ms-BN', flag: '🇧🇳' },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'DT', locale: 'ar-TN', flag: '🇹🇳' },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'DA', locale: 'ar-DZ', flag: '🇩🇿' },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'LD', locale: 'ar-LY', flag: '🇱🇾' },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'SDG', locale: 'ar-SD', flag: '🇸🇩' },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh', locale: 'so-SO', flag: '🇸🇴' },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', locale: 'fr-DJ', flag: '🇩🇯' },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', locale: 'ti-ER', flag: '🇪🇷' },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', locale: 'en-MW', flag: '🇲🇼' },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', locale: 'mg-MG', flag: '🇲🇬' },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', locale: 'en-GM', flag: '🇬🇲' },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', locale: 'fr-GN', flag: '🇬🇳' },
  { code: 'SLL', name: 'Sierra Leonean Leone', symbol: 'Le', locale: 'en-SL', flag: '🇸🇱' },
  { code: 'LRD', name: 'Liberian Dollar', symbol: 'L$', locale: 'en-LR', flag: '🇱🇷' },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'Esc', locale: 'pt-CV', flag: '🇨🇻' },
  { code: 'STN', name: 'São Tomé Dobra', symbol: 'Db', locale: 'pt-ST', flag: '🇸🇹' },
  { code: 'NAD', name: 'Namibian Dollar', symbol: 'N$', locale: 'en-NA', flag: '🇳🇦' },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', locale: 'en-SZ', flag: '🇸🇿' },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', locale: 'en-LS', flag: '🇱🇸' },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', locale: 'fr-BI', flag: '🇧🇮' },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', locale: 'fr-CD', flag: '🇨🇩' },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', locale: 'fr-KM', flag: '🇰🇲' },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', locale: 'ar-YE', flag: '🇾🇪' },
  { code: 'SYP', name: 'Syrian Pound', symbol: 'S£', locale: 'ar-SY', flag: '🇸🇾' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', locale: 'ar-MR', flag: '🇲🇷' },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', locale: 'tg-TJ', flag: '🇹🇯' },
  { code: 'KGS', name: 'Kyrgyzstani Som', symbol: 'сом', locale: 'ky-KG', flag: '🇰🇬' },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', locale: 'tk-TM', flag: '🇹🇲' },
];

/** Mapping from country code to currency code for auto-detection */
export const countryToCurrency: Record<string, string> = {
  US: 'USD', GB: 'GBP', DE: 'EUR', FR: 'EUR', IT: 'EUR', ES: 'EUR', NL: 'EUR',
  BE: 'EUR', AT: 'EUR', IE: 'EUR', PT: 'EUR', FI: 'EUR', GR: 'EUR', LU: 'EUR',
  SK: 'EUR', SI: 'EUR', EE: 'EUR', LT: 'EUR', LV: 'EUR', MT: 'EUR', CY: 'EUR',
  JP: 'JPY', CN: 'CNY', IN: 'INR', CA: 'CAD', AU: 'AUD', CH: 'CHF', KR: 'KRW',
  SG: 'SGD', HK: 'HKD', SE: 'SEK', NO: 'NOK', DK: 'DKK', NZ: 'NZD', MX: 'MXN',
  BR: 'BRL', AR: 'ARS', CL: 'CLP', CO: 'COP', PE: 'PEN', ZA: 'ZAR', NG: 'NGN',
  GH: 'GHS', KE: 'KES', UG: 'UGX', TZ: 'TZS', ET: 'ETB', EG: 'EGP', MA: 'MAD',
  SN: 'XOF', CM: 'XAF', RW: 'RWF', ZM: 'ZMW', BW: 'BWP', MZ: 'MZN', AO: 'AOA',
  TR: 'TRY', RU: 'RUB', UA: 'UAH', PL: 'PLN', CZ: 'CZK', HU: 'HUF', RO: 'RON',
  BG: 'BGN', HR: 'EUR', RS: 'RSD', IS: 'ISK', AE: 'AED', SA: 'SAR', QA: 'QAR',
  KW: 'KWD', BH: 'BHD', OM: 'OMR', JO: 'JOD', IL: 'ILS', LB: 'LBP', PK: 'PKR',
  BD: 'BDT', LK: 'LKR', NP: 'NPR', TH: 'THB', VN: 'VND', MY: 'MYR', ID: 'IDR',
  PH: 'PHP', TW: 'TWD', MM: 'MMK', KH: 'KHR', LA: 'LAK', MN: 'MNT', KZ: 'KZT',
  UZ: 'UZS', GE: 'GEL', AM: 'AMD', AZ: 'AZN', IQ: 'IQD', IR: 'IRR', AF: 'AFN',
  DO: 'DOP', CR: 'CRC', GT: 'GTQ', HN: 'HNL', NI: 'NIO', PA: 'PAB', UY: 'UYU',
  PY: 'PYG', BO: 'BOB', VE: 'VES', JM: 'JMD', TT: 'TTD', BB: 'BBD', BS: 'BSD',
  HT: 'HTG', CU: 'CUP', BZ: 'BZD', SR: 'SRD', GY: 'GYD', FJ: 'FJD', PG: 'PGK',
  WS: 'WST', TO: 'TOP', VU: 'VUV', SB: 'SBD', SC: 'SCR', MU: 'MUR', MV: 'MVR',
  BN: 'BND', TN: 'TND', DZ: 'DZD', LY: 'LYD', SD: 'SDG', SO: 'SOS', DJ: 'DJF',
  ER: 'ERN', MW: 'MWK', MG: 'MGA', GM: 'GMD', GN: 'GNF', SL: 'SLL', LR: 'LRD',
  CV: 'CVE', ST: 'STN', NA: 'NAD', SZ: 'SZL', LS: 'LSL', BI: 'BIF', CD: 'CDF',
  KM: 'KMF', YE: 'YER', SY: 'SYP', MR: 'MRU', TJ: 'TJS', KG: 'KGS', TM: 'TMT',
};

/** Get currency info by code */
export function getCurrencyByCode(code: string): CurrencyInfo | undefined {
  return currencies.find((c) => c.code === code);
}

/** Search currencies by name or code */
export function searchCurrencies(query: string): CurrencyInfo[] {
  const q = query.toLowerCase().trim();
  if (!q) return currencies;
  return currencies.filter(
    (c) =>
      c.code.toLowerCase().includes(q) ||
      c.name.toLowerCase().includes(q) ||
      c.symbol.toLowerCase().includes(q) ||
      (currencyKeywords[c.code] && currencyKeywords[c.code].includes(q)),
  );
}

/** Mapping of currency codes to their associated country names for robust searching */
export const currencyKeywords: Record<string, string> = {
  EUR: 'germany france italy spain netherlands belgium austria ireland portugal finland greece luxembourg slovakia slovenia estonia lithuania latvia malta cyprus andorra monaco san marino vatican montenegro kosovo',
  XOF: 'senegal ivory coast cote d\'ivoire burkina faso benin mali niger togo guinea-bissau',
  XAF: 'cameroon central african republic chad republic of the congo equatorial guinea gabon',
  USD: 'united states america us usa ecuador el salvador zimbabwe puerto rico panama',
  GBP: 'united kingdom britain england scotland wales northern ireland uk',
  AUD: 'australia nauru tuvalu kiribati',
  NZD: 'new zealand cook islands niue pitcairn tokelau',
  CHF: 'switzerland liechtenstein',
  INR: 'india bhutan',
  ZAR: 'south africa lesotho namibia',
  CAD: 'canada',
  CNY: 'china',
  JPY: 'japan',
  KRW: 'south korea',
  MXN: 'mexico',
  BRL: 'brazil',
  ARS: 'argentina',
  CLP: 'chile',
  COP: 'colombia',
  PEN: 'peru',
  NGN: 'nigeria',
  GHS: 'ghana',
  KES: 'kenya',
  UGX: 'uganda',
  TZS: 'tanzania',
  ETB: 'ethiopia',
  EGP: 'egypt',
  MAD: 'morocco',
  ZMW: 'zambia',
  BWP: 'botswana',
  MZN: 'mozambique',
  AOA: 'angola',
  TRY: 'turkey',
  RUB: 'russia',
  UAH: 'ukraine',
  PLN: 'poland',
  CZK: 'czech republic czechia',
  HUF: 'hungary',
  RON: 'romania',
  BGN: 'bulgaria',
  HRK: 'croatia',
  RSD: 'serbia',
  ISK: 'iceland',
  AED: 'uae united arab emirates dubai',
  SAR: 'saudi arabia',
  QAR: 'qatar',
  KWD: 'kuwait',
  BHD: 'bahrain',
  OMR: 'oman',
  JOD: 'jordan',
  ILS: 'israel palestine',
  LBP: 'lebanon',
  PKR: 'pakistan',
  BDT: 'bangladesh',
  LKR: 'sri lanka',
  NPR: 'nepal',
  THB: 'thailand',
  VND: 'vietnam',
  MYR: 'malaysia',
  IDR: 'indonesia',
  PHP: 'philippines',
  TWD: 'taiwan',
  MMK: 'myanmar burma',
  KHR: 'cambodia',
  LAK: 'laos',
  MNT: 'mongolia',
  KZT: 'kazakhstan',
  UZS: 'uzbekistan',
  GEL: 'georgia',
  AMD: 'armenia',
  AZN: 'azerbaijan',
  IQD: 'iraq',
  IRR: 'iran',
  AFN: 'afghanistan',
  DOP: 'dominican republic',
  CRC: 'costa rica',
  GTQ: 'guatemala',
  HNL: 'honduras',
  NIO: 'nicaragua',
  PAB: 'panama',
  UYU: 'uruguay',
  PYG: 'paraguay',
  BOB: 'bolivia',
  VES: 'venezuela',
  JMD: 'jamaica',
  TTD: 'trinidad tobago',
  BBD: 'barbados',
  BSD: 'bahamas',
  HTG: 'haiti',
  CUP: 'cuba',
  BZD: 'belize',
  SRD: 'suriname',
  GYD: 'guyana',
  FJD: 'fiji',
  PGK: 'papua new guinea',
  WST: 'samoa',
  TOP: 'tonga',
  VUV: 'vanuatu',
  SBD: 'solomon islands',
  SCR: 'seychelles',
  MUR: 'mauritius',
  MVR: 'maldives',
  BND: 'brunei',
  TND: 'tunisia',
  DZD: 'algeria',
  LYD: 'libya',
  SDG: 'sudan',
  SOS: 'somalia',
  DJF: 'djibouti',
  ERN: 'eritrea',
  MWK: 'malawi',
  MGA: 'madagascar',
  GMD: 'gambia',
  GNF: 'guinea',
  SLL: 'sierra leone',
  LRD: 'liberia',
  CVE: 'cape verde',
  STN: 'sao tome',
  NAD: 'namibia',
  SZL: 'eswatini swaziland',
  LSL: 'lesotho',
  BIF: 'burundi',
  CDF: 'congo',
  KMF: 'comoros',
  YER: 'yemen',
  SYP: 'syria',
  MRU: 'mauritania',
  TJS: 'tajikistan',
  KGS: 'kyrgyzstan',
  TMT: 'turkmenistan',
};
